config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sublots
  resources :costcs
  resources :labors
  resources :supervisors
  resources :jobs
  resources :operators

devise_scope :user do
  authenticated :user do
    root 'plainpage#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

     namespace :admin do

       post 'operators/retired/:id', to: 'operators#retired', as: 'retired_operator'
       post 'operators/reinstated/:id', to: 'operators#reinstated', as: 'reinstated_operator'
       post 'operators/enable/:id', to: 'operators#enable', as: 'enable_operator'
       post 'operators/changedjob/:id', to: 'operators#changedjob', as: 'changedjob_operator'
       get 'operators/retire/:id', to: 'operators#retire', as: 'retire_operator'
       get 'operators/reinstate/:id', to: 'operators#reinstate', as: 'reinstate_operator'
       get 'operators/activate/:id', to: 'operators#activate', as: 'activate_operator'
       get 'operators/changejob/:id', to: 'operators#changejob', as: 'changejob_operator'
       get 'operators/savehistory'
       get 'operators/paysheet/:fromdate/:todate/:paydate/:companytype', to: 'operators#paysheet', as: 'operators_paysheet'
       post 'operators/paysheet_post', to: 'operators#paysheet_post', as: 'paysheet_post'
       get 'operators/liquidate/:fromdate/:todate/:paydate/:companytype', to: 'operators#liquidate', as: 'operators_liquidate'
       post 'operators/liquidate_post', to: 'operators#liquidate_post', as: 'liquidate_post'

       resources :operators

       resources :jobs
       get 'jobs/disable/:id', to: 'jobs#disable', as: 'disable_job'
       get 'jobs/enable/:id', to: 'jobs#enable', as: 'enable_job'

       post 'supervisors/:id/retired', to: 'supervisors#retired', as: 'retired_supervisor'
       post 'supervisors/:id/reinstated', to: 'supervisors#reinstated', as: 'reinstated_supervisor'
       post 'supervisors/:id/enable', to: 'supervisors#enable', as: 'enable_supervisor'
       get 'supervisors/:id/retire', to: 'supervisors#retire', as: 'retire_supervisor'
       get 'supervisors/:id/reinstate', to: 'supervisors#reinstate', as: 'reinstate_supervisor'
       get 'supervisors/:id/activate', to: 'supervisors#activate', as: 'activate_supervisor'
       get 'supervisors/register', to: 'supervisors#register', as: 'register_supervisor'

       get 'transcriptions/get_labors/:operatorId', to: 'transcriptions#get_labors', as: 'get_labors'
       get 'transcriptions/get_sublots/:costcId', to: 'transcriptions#get_sublots', as: 'get_sublots'

       get 'novelties/get_employeelabors/:supervisorId', to: 'novelties#get_employeelabors', as: 'get_employeelabors'

       get 'configs/index', to: 'configs#index', as: 'index_config'
       get 'configs/edit', to: 'configs#edit', as: 'edit_config'
       patch 'configs/update', to: 'configs#update', as: 'update_config'

       get 'registers/index', to: 'registers#index', as: 'index_register'
       post 'registers/create', to: 'registers#create', as: 'create_register'
       get 'registers/new', to: 'registers#new', as: 'new_register'
       get 'registers/edit/:id', to: 'registers#edit', as: 'edit_register'
       patch 'registers/update/:id', to: 'registers#update', as: 'update_register'

       resources :supervisors

       resources :labors

       resources :costcs

       resources :sublots

       resources :transcriptions
       
       resources :novelties

       resources :billingcs

       resources :companies

     end
end

app/models/billingc.rb
class Billingc < ActiveRecord::Base
	has_many :operator
	has_many :supervisor
end

app/controllers/admin/billingcs_controller.rb
class Admin::BillingcsController < ApplicationController

  def index
    @billingcs = Billingc.all
  end

  # GET /operators/new
  def new
    @billingc = Billingc.new
  end

  def create
    @billingc = Billingc.new(billingc_params)

    if @billingc.save
      redirect_to admin_billingcs_path, notice: 'Centro de facturación creado satisfactoriamente'
    else
      render :new , alert: 'Centro de facturación no creado satisfactoriamente' 
    end
  end

  def edit
    @billingc = Billingc.find(params[:id])
  end

  def update
    @billingc = Billingc.find(params[:id])

    if @billingc.update(billingc_params)
      redirect_to  admin_billingcs_path, notice: 'Centro de facturación editado satisfactoriamente'
    else
      render :new , alert: 'Centro de facturación no editado satisfactoriamente' 
    end
  end

  def destroy
    @billingc = Billingc.find(params[:id])
    @billingc.destroy
 
    redirect_to admin_billingcs_path
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def billingc_params
      params.require(:billingc).permit(:name, :description)
    end
end

app/views/admin/billingcs/edit.html.erb
<h1 class="x_title">
  <i class="glyphicon glyphicon-leaf titleicon"></i>
  Crear centro de facturación
</h1>

<%= form_for @billingc , url:{action: "update"} do |f| %>

  <% if @billingc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@billingc.errors.count, "error") %> prohibited this billingc from being saved:</h2>
      <ul>
        <% @billingc.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-12 field">
    <div class="col-md-12">
      <%= f.label :name, "Nombre"%>
      <%= f.text_field :name , class:"form-control"%>
    </div>
  </div>
  <div class="form-group col-md-12 field">
    <div class="col-md-12">
      <%= f.label :description, "Descripción"%>
      <%= f.text_area :description , class:"form-control"%>
    </div>
  </div>

  <div class="form-group col-md-12 field">
    <div class="col-md-12">
      <%= button_tag(:type => 'submit', :class => 'btn btn-dark') do %>
        <i class="glyphicon glyphicon-floppy-disk"></i>
        Crear centro de facturación 
      <% end %>
      <%= link_to admin_billingcs_path ,:class =>"btn btn-danger" do %>
        <span class="glyphicon glyphicon-remove"></span>
        Cancelar
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/billingcs/index.html.erb
<%= javascript_include_tag 'jquery.dataTables.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'bootstrap', 'data-turbolinks-track' => true %>

<h1 class="x_title">
<i class="glyphicon glyphicon-leaf titleicon"></i>
Listar Centros de facturación
</h1>

<%= link_to new_admin_billingc_path , :class =>"btn btn-dark pull-right" do%>
  <span class="glyphicon glyphicon-plus"></span>
  Crear centro de facturación
<% end %>

<table id="datatable" class="display datatable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
    <% @billingcs.each do |billingc| %>
      <tr>
        <td><%= billingc.name %></td>
        <td><%= billingc.description %></td>
        <td>
          <%= link_to edit_admin_billingc_path(billingc),:class =>"btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-pencil"></span>
            Editar
          <%end%>
          <%= link_to admin_billingc_path(billingc),:class =>"btn btn-default btn-sm", method: :delete, data: { confirm: '¿Seguro desea eliminar el registro?' } do %>
            <span class="glyphicon glyphicon-trash"></span>
            Eliminar
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
$('#datatable').DataTable({
              "language": {
                "url": "files/spanish"
            }
  // ajax: ...,
  // autoWidth: false,
  // pagingType: 'full_numbers',
  // processing: true,
  // serverSide: true,

  // Optional, if you want full pagination controls.
  // Check dataTables documentation to learn more about available options.
  // http://datatables.net/reference/option/pagingType
});
</script>

app/views/admin/billingcs/new.html.erb
<h1 class="x_title">
  <i class="glyphicon glyphicon-leaf titleicon"></i>
  Crear centro de facturación
</h1>

<%= form_for @billingc , url:{action: "create"} do |f| %>

  <% if @billingc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@billingc.errors.count, "error") %> prohibited this billingc from being saved:</h2>
      <ul>
        <% @billingc.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-12 field">
    <div class="col-md-12">
      <%= f.label :name, "Nombre"%>
      <%= f.text_field :name , class:"form-control"%>
    </div>
  </div>
  <div class="form-group col-md-12 field">
    <div class="col-md-12">
      <%= f.label :description, "Descripción"%>
      <%= f.text_area :description , class:"form-control"%>
    </div>
  </div>

  <div class="form-group col-md-12 field">
    <div class="col-md-12">
      <%= button_tag(:type => 'submit', :class => 'btn btn-dark') do %>
        <i class="glyphicon glyphicon-floppy-disk"></i>
        Crear centro de facturación 
      <% end %>
      <%= link_to admin_billingcs_path ,:class =>"btn btn-danger" do %>
        <span class="glyphicon glyphicon-remove"></span>
        Cancelar
      <% end %>
    </div>
  </div>
<% end %>