config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sublots
  resources :costcs
  resources :labors
  resources :supervisors
  resources :jobs
  resources :operators

devise_scope :user do
  authenticated :user do
    root 'plainpage#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

     namespace :admin do

       post 'operators/retired/:id', to: 'operators#retired', as: 'retired_operator'
       post 'operators/reinstated/:id', to: 'operators#reinstated', as: 'reinstated_operator'
       post 'operators/enable/:id', to: 'operators#enable', as: 'enable_operator'
       post 'operators/changedjob/:id', to: 'operators#changedjob', as: 'changedjob_operator'
       get 'operators/retire/:id', to: 'operators#retire', as: 'retire_operator'
       get 'operators/reinstate/:id', to: 'operators#reinstate', as: 'reinstate_operator'
       get 'operators/activate/:id', to: 'operators#activate', as: 'activate_operator'
       get 'operators/changejob/:id', to: 'operators#changejob', as: 'changejob_operator'
       get 'operators/savehistory'
       get 'operators/paysheet/:fromdate/:todate/:paydate/:companytype', to: 'operators#paysheet', as: 'operators_paysheet'
       post 'operators/paysheet_post', to: 'operators#paysheet_post', as: 'paysheet_post'
       get 'operators/liquidate/:fromdate/:todate/:paydate/:companytype', to: 'operators#liquidate', as: 'operators_liquidate'
       post 'operators/liquidate_post', to: 'operators#liquidate_post', as: 'liquidate_post'

       resources :operators

       resources :jobs
       get 'jobs/disable/:id', to: 'jobs#disable', as: 'disable_job'
       get 'jobs/enable/:id', to: 'jobs#enable', as: 'enable_job'

       post 'supervisors/:id/retired', to: 'supervisors#retired', as: 'retired_supervisor'
       post 'supervisors/:id/reinstated', to: 'supervisors#reinstated', as: 'reinstated_supervisor'
       post 'supervisors/:id/enable', to: 'supervisors#enable', as: 'enable_supervisor'
       get 'supervisors/:id/retire', to: 'supervisors#retire', as: 'retire_supervisor'
       get 'supervisors/:id/reinstate', to: 'supervisors#reinstate', as: 'reinstate_supervisor'
       get 'supervisors/:id/activate', to: 'supervisors#activate', as: 'activate_supervisor'
       get 'supervisors/register', to: 'supervisors#register', as: 'register_supervisor'

       get 'transcriptions/get_labors/:operatorId', to: 'transcriptions#get_labors', as: 'get_labors'
       get 'transcriptions/get_sublots/:costcId', to: 'transcriptions#get_sublots', as: 'get_sublots'

       get 'novelties/get_employeelabors/:supervisorId', to: 'novelties#get_employeelabors', as: 'get_employeelabors'

       get 'configs/index', to: 'configs#index', as: 'index_config'
       get 'configs/edit', to: 'configs#edit', as: 'edit_config'
       patch 'configs/update', to: 'configs#update', as: 'update_config'

       get 'registers/index', to: 'registers#index', as: 'index_register'
       post 'registers/create', to: 'registers#create', as: 'create_register'
       get 'registers/new', to: 'registers#new', as: 'new_register'
       get 'registers/edit/:id', to: 'registers#edit', as: 'edit_register'
       patch 'registers/update/:id', to: 'registers#update', as: 'update_register'

       resources :supervisors

       resources :labors

       resources :costcs

       resources :sublots

       resources :transcriptions
       
       resources :novelties

       resources :billingcs

       resources :companies

     end
end

app/models/job.rb
class Job < ActiveRecord::Base
	has_many :operators

	has_many :supervisors

	has_many :labors, through: :labor_job
	has_many :labor_job

	belongs_to :recordjob

	has_many :transcriptions

	has_many :novelties

	attr_accessor :labors2
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  def enable
    @job = Job.find(params[:id])
    @job[:state] = "Activo"
    if @job.save
      redirect_to admin_jobs_path, notice: 'Estado habilitado satisfactoriamente'
    else
      render :new , alert: 'Estado no habilitado satisfactoriamente' 
    end
  end

  def disable
    @job = Job.find(params[:id])
    @job[:state] = "Inactivo"
    if @job.save
      redirect_to admin_jobs_path, notice: 'Estado inhabilitado satisfactoriamente'
    else
      render :new , alert: 'Estado no inhabilitado satisfactoriamente' 
    end
  end


  def create
    @job = Job.new(job_params)
    @job.state="Activo"
    @job[:state]= 1

    if @job.save

      params[:job][:labors2].each do |labor|
        if labor.present?
          nuevo = LaborJob.new
          nuevo[:labor_id] = labor
          nuevo[:job_id] = @job.id
          nuevo.save
        end
      end

      redirect_to admin_jobs_path, notice: 'C1argo creado satisfactoriamente'
    else
      render :new , alert: 'Cargo no creado satisfactoriamente' 
    end
  end


  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    if @job.labors.present?
      @job = Job.find(params[:id])
      @job.labors.delete_all
    end

    params[:job][:labors2].each do |labor|
      if labor.present?
        nuevo = LaborJob.new
        nuevo[:labor_id] = labor
        nuevo[:job_id] = @job.id
        nuevo.save
      end
    end
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to admin_jobs_path, notice: 'Cargo editado satisfactoriamente' }
      else
        render :edit , alert: 'Cargo no creado satisfactoriamente' 
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.where(id: params[:id]).first

    if JobOperator.where(job_id: params[:id]).first.present?     
      respond_to do |format|
        format.html { redirect_to admin_jobs_path, alert: 'Este operador no se puede eliminar, tiene registros en el sistema' }
      end
    else
      @job[:flag] = 0
      @job.save
      respond_to do |format|
        format.html { redirect_to admin_jobs_path, notice: 'Operador eliminado satisfactoriamente' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:user_id, :name, :description, :basepay)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  def change
    @jobs = Job.all
  end


  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path, notice: 'Cargo creado satisfactoriamente'
    else
      render :new , alert: 'Cargo no creado satisfactoriamente' 
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to jobs_path, notice: 'Cargo editado satisfactoriamente' }
      else
        render :new , alert: 'Cargo no editado satisfactoriamente' 
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_path, notice: 'Cargo eliminado satisfactoriamente' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:user_id, :name, :description, :state)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/jobs/edit.html.erb
<%= stylesheet_link_tag    'selectize.bootstrap3', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'selectize', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'plugin', 'data-turbolinks-track' => true %>

<h1 class="x_title">
	<i class="glyphicon glyphicon-leaf titleicon"></i>
	Editar Cargo
</h1>

<%= form_for @job, url:{action: "update"} do |f| %>
	<% if @job.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>
	  <ul>
	  	<% @job.errors.full_messages.each do |message| %>
	    <li><%= message %></li>
	  <% end %>
	  </ul>
	</div>
	<% end %>

	<div class="form-group col-md-12 field">
		<div class="col-md-6">
			<%= f.label :name , "Nombre" %>
			<%= f.text_field :name , class:"form-control"%>
		</div>
		<div class="col-md-6">
			<%= f.label :basepay , "Básico" %>
			<%= f.text_field :basepay , class:"form-control"%>
		</div>
	</div>
	<div class="form-group col-md-12 field">
		<div class="col-md-12">
			<%= f.label :labors2 , "Labores"%><br>
			<%= f.select :labors2 , Labor.all.map { |j|  [ j.code + " " + j.name , j.id ]  } , {selected: @job.labors.map { |e| e.id }}, {:multiple => true, class:"form-control"} %>
		</div>
	</div>
	<div class="form-group col-md-12 field">
		<div class="col-md-12">
			<%= f.label :description , "Descripción" %>
			<%= f.text_area :description , class:"form-control"%>
		</div>
	</div>

  <div class="form-group col-md-12 field">
    <div class="col-md-12">
      <%= button_tag(:type => 'submit', :class => 'btn btn-dark') do %>
        <i class="glyphicon glyphicon-floppy-disk"></i>
        Editar cargo 
      <% end %>
      <%= link_to admin_jobs_path ,:class =>"btn btn-danger" do %>
        <span class="glyphicon glyphicon-remove"></span>
        Cancelar
      <% end %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
$("#job_labors2").selectize({ plugins: ['remove_button'] });
</script>

app/views/admin/jobs/index.html.erb
<%= javascript_include_tag 'jquery.dataTables.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'bootstrap', 'data-turbolinks-track' => true %>

<h1 class="x_title"><i class="glyphicon glyphicon-leaf titleicon"></i>Listar Cargos</h1>

<%= link_to new_admin_job_path , :class =>"btn btn-dark pull-right" do%>
  <span class="glyphicon glyphicon-plus"></span>
  Crear cargo
<% end %>

<table id="datatable" class="display datatable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Básico</th>
      <th>Estado</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.name %></td>
        <td><%= job.basepay %></td>
        <td><%= job.state %></td>
        <td>

        <%= link_to admin_job_path(job),:class =>"btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-eye-open"></span>
          Ver
        <%end%>

        <%= link_to edit_admin_job_path(job),:class =>"btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-pencil"></span>
          Editar
        <%end%>

        <%= link_to admin_job_path(job),:class =>"btn btn-default btn-sm", method: :delete, data: { confirm: '¿Seguro desea eliminar el cargo?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
          Eliminar
        <%end%>

        <%if job.state=="Inactivo"%>
          <%= link_to admin_enable_job_path(job),:class =>"btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-export"></span>
            Habilitar
          <%end%>
        <%else%>
          <%= link_to admin_disable_job_path(job),:class =>"btn btn-default btn-sm" do %>
            <span class="glyphicon glyphicon-import"></span>
            Deshabilitar
          <%end%>
        <%end%>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
$('#datatable').DataTable({
              "language": {
                "url": "../files/spanish"
            }
  // ajax: ...,
  // autoWidth: false,
  // pagingType: 'full_numbers',
  // processing: true,
  // serverSide: true,

  // Optional, if you want full pagination controls.
  // Check dataTables documentation to learn more about available options.
  // http://datatables.net/reference/option/pagingType
});
</script>

app/views/admin/jobs/new.html.erb
<%= stylesheet_link_tag    'selectize.bootstrap3', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'selectize', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'plugin', 'data-turbolinks-track' => true %>

<h1 class="x_title">
  <i class="glyphicon glyphicon-leaf titleicon"></i>
  Crear Cargo
</h1>

<%= form_for @job, url:{action: "create"} do |f| %>

  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>
      <ul>
      	<% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group col-md-12 field">
    <div class="col-md-6">
      <%= f.label :name , "Nombre"%>
      <%= f.text_field :name , class:"form-control"%>
    </div>
    <div class="col-md-6">
      <%= f.label :basepay , "Básico"%>
      <%= f.text_field :basepay , class:"form-control"%>
    </div>
  </div>
  <div class="form-group col-md-12 field">
    <div class="col-md-12">
      <%= f.label :labors2 , "Labores"%><br>
      <%= f.select :labors2 , Labor.all.map { |j|  [ j.code + " " + j.name , j.id ]  } , {}, {:multiple => true, class:"form-control"} %>
    </div>
  </div>
  <div class="form-group col-md-12 field">
    <div class="col-md-12">
      <%= f.label :description , "Descripción"%>
      <%= f.text_area :description , class:"form-control"%>
    </div>
  </div>

  <div class="form-group col-md-12 field">
    <div class="col-md-12">
      <%= button_tag(:type => 'submit', :class => 'btn btn-dark') do %>
        <i class="glyphicon glyphicon-floppy-disk"></i>
        Crear cargo 
      <% end %>
      <%= link_to admin_jobs_path ,:class =>"btn btn-danger" do %>
        <span class="glyphicon glyphicon-remove"></span>
        Cancelar
      <% end %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
$("#job_labors2").selectize({ plugins: ['remove_button'] });
</script>

app/views/admin/jobs/show.html.erb
<div class="x_panel">

	<h1 class="x_title">
		<i class="glyphicon glyphicon-leaf titleicon"></i>
		Cargo: <%= @job.name %>
	</h1>

	<h4>Básico:
	  <%= @job.basepay %>
	</h4>

	<p>
	  <strong>Descripción:</strong>
	  <%= @job.description %>
	</p>

	<p>
	  <strong>Labores asociadas:</strong>
	  <%= @job.labors.map { |e| e.code + " " + e.name }.join("<br>").html_safe %>
	</p>

	<p>
	<strong>Labores asociadas:</strong>
	</p>

	<div class="x_content">
		<table class="table table-bordered" width="100%">
		  <thead>
		    <tr>
		      <th class="active">Código</th>
		      <th class="active">Nombre</th>
		    </tr>
		  </thead>
		<tbody>
		  <% @job.labors.each do |labor| %>
		      <tr>
		        <td><%= labor.code %></td>
		        <td><%= labor.name %></td>
		      </tr>
		  <% end %>
		</tbody>
		</table>

		<%= link_to edit_admin_job_path(@job),:class =>"btn btn-dark" do %>
			<span class="glyphicon glyphicon-pencil"></span>
			Editar
		<% end %>

		<%= link_to admin_jobs_path, :class =>"btn btn-danger" do %>
			<span class="glyphicon glyphicon-remove"></span>
			Cancelar
		<% end %>
	</div>
</div>