config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :sublots
  resources :costcs
  resources :labors
  resources :supervisors
  resources :jobs
  resources :operators

devise_scope :user do
  authenticated :user do
    root 'plainpage#index', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

     namespace :admin do

       post 'operators/retired/:id', to: 'operators#retired', as: 'retired_operator'
       post 'operators/reinstated/:id', to: 'operators#reinstated', as: 'reinstated_operator'
       post 'operators/enable/:id', to: 'operators#enable', as: 'enable_operator'
       post 'operators/changedjob/:id', to: 'operators#changedjob', as: 'changedjob_operator'
       get 'operators/retire/:id', to: 'operators#retire', as: 'retire_operator'
       get 'operators/reinstate/:id', to: 'operators#reinstate', as: 'reinstate_operator'
       get 'operators/activate/:id', to: 'operators#activate', as: 'activate_operator'
       get 'operators/changejob/:id', to: 'operators#changejob', as: 'changejob_operator'
       get 'operators/savehistory'
       get 'operators/paysheet/:fromdate/:todate/:paydate/:companytype', to: 'operators#paysheet', as: 'operators_paysheet'
       post 'operators/paysheet_post', to: 'operators#paysheet_post', as: 'paysheet_post'
       get 'operators/liquidate/:fromdate/:todate/:paydate/:companytype', to: 'operators#liquidate', as: 'operators_liquidate'
       post 'operators/liquidate_post', to: 'operators#liquidate_post', as: 'liquidate_post'

       resources :operators

       resources :jobs
       get 'jobs/disable/:id', to: 'jobs#disable', as: 'disable_job'
       get 'jobs/enable/:id', to: 'jobs#enable', as: 'enable_job'

       post 'supervisors/:id/retired', to: 'supervisors#retired', as: 'retired_supervisor'
       post 'supervisors/:id/reinstated', to: 'supervisors#reinstated', as: 'reinstated_supervisor'
       post 'supervisors/:id/enable', to: 'supervisors#enable', as: 'enable_supervisor'
       get 'supervisors/:id/retire', to: 'supervisors#retire', as: 'retire_supervisor'
       get 'supervisors/:id/reinstate', to: 'supervisors#reinstate', as: 'reinstate_supervisor'
       get 'supervisors/:id/activate', to: 'supervisors#activate', as: 'activate_supervisor'
       get 'supervisors/register', to: 'supervisors#register', as: 'register_supervisor'

       get 'transcriptions/get_labors/:operatorId', to: 'transcriptions#get_labors', as: 'get_labors'
       get 'transcriptions/get_sublots/:costcId', to: 'transcriptions#get_sublots', as: 'get_sublots'

       get 'novelties/get_employeelabors/:supervisorId', to: 'novelties#get_employeelabors', as: 'get_employeelabors'

       get 'configs/index', to: 'configs#index', as: 'index_config'
       get 'configs/edit', to: 'configs#edit', as: 'edit_config'
       patch 'configs/update', to: 'configs#update', as: 'update_config'

       get 'registers/index', to: 'registers#index', as: 'index_register'
       post 'registers/create', to: 'registers#create', as: 'create_register'
       get 'registers/new', to: 'registers#new', as: 'new_register'
       get 'registers/edit/:id', to: 'registers#edit', as: 'edit_register'
       patch 'registers/update/:id', to: 'registers#update', as: 'update_register'

       resources :supervisors

       resources :labors

       resources :costcs

       resources :sublots

       resources :transcriptions
       
       resources :novelties

       resources :billingcs

       resources :companies

     end
end

app/models/sublot.rb
class Sublot < ActiveRecord::Base
	belongs_to :costc

	has_many :transcriptions
end

app/controllers/admin/sublots_controller.rb
class Admin::SublotsController < ApplicationController
  before_action :set_sublot, only: [:show, :edit, :update, :destroy]

  # GET /sublots
  # GET /sublots.json
  def index
    @sublots = Sublot.all
  end

  # GET /sublots/1
  # GET /sublots/1.json
  def show
  end

  # GET /sublots/new
  def new
    @sublot = Sublot.new
  end

  # GET /sublots/1/edit
  def edit
  end


  def create
    @sublot = Sublot.new(sublot_params)
      if @sublot.save
        redirect_to admin_sublots_path, notice: 'Sublote creado satisfactoriamente'
      else
        render :new , alert: 'Sublote no creado satisfactoriamente'
      end
  end


  # PATCH/PUT /sublots/1
  # PATCH/PUT /sublots/1.json
  def update
    respond_to do |format|
      if @sublot.update(sublot_params)
        format.html { redirect_to admin_sublots_path, notice: 'Sublote editado satisfactoriamente' }
      else
        render :edit , alert: 'Sublote no creado satisfactoriamente' 
      end
    end
  end

  # DELETE /sublots/1
  # DELETE /sublots/1.json
  def destroy
    @sublot.destroy
    respond_to do |format|
      format.html { redirect_to admin_sublots_path, notice: 'Sublote eliminado satisfactoriamente' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sublot
      @sublot = Sublot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sublot_params
      params.require(:sublot).permit(:user_id, :name, :description, :code, :costc_id)
    end
end

app/controllers/sublots_controller.rb
class SublotsController < ApplicationController
  before_action :set_sublot, only: [:show, :edit, :update, :destroy]

  # GET /sublots
  # GET /sublots.json
  def index
    @sublots = Sublot.all
  end

  # GET /sublots/1
  # GET /sublots/1.json
  def show
  end

  # GET /sublots/new
  def new
    @sublot = Sublot.new
  end

  # GET /sublots/1/edit
  def edit
  end

  # POST /sublots
  # POST /sublots.json
  def create
    @sublot = Sublot.new(sublot_params)
      if @sublot.save
        redirect_to sublots_path, notice: 'Sublote creado satisfactoriamente'
      else
        render :new , alert: 'Sublote no creado satisfactoriamente'
      end
  end

  # PATCH/PUT /sublots/1
  # PATCH/PUT /sublots/1.json
  def update
    respond_to do |format|
      if @sublot.update(sublot_params)
        format.html { redirect_to sublots_path, notice: 'Sublote editado satisfactoriamente' }
      else
        render :edit, alert: 'Sublote no editado satisfactoriamente'
      end
    end
  end

  # DELETE /sublots/1
  # DELETE /sublots/1.json
  def destroy
    @sublot.destroy
    respond_to do |format|
      format.html { redirect_to sublots_path, notice: 'Sublote eliminado satisfactoriamente' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sublot
      @sublot = Sublot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sublot_params
      params.require(:sublot).permit(:code, :name, :user_id, :description)
    end
end

app/helpers/sublots_helper.rb
module SublotsHelper
end

app/views/admin/sublots/_form.html.erb
<%= form_for(@sublot) do |f| %>
  <% if @sublot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sublot.errors.count, "error") %> prohibited this sublot from being saved:</h2>

      <ul>
      <% @sublot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/sublots/edit.html.erb
<h1 class="x_title">
  <i class="glyphicon glyphicon-leaf titleicon"></i>
  Editar Sublote
</h1>

<%= form_for @sublot , url:{action: "update"} do |f| %>
  <% if @sublot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sublot.errors.count, "error") %> prohibited this sublot from being saved:</h2>
      <ul>
      	<% @sublot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group col-md-12">
    <div class="col-md-4">
        <%= f.label :costc_id, "Centro de costo", class:"subtitle"%>
        <%= f.select :costc_id, Costc.all.map { |j|  [ j.name , j.id ]  } , {prompt: ""} ,class:"form-control"%>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :code , "Código"%><br>
      <%= f.text_field :code , class:"form-control"%>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :name , "Nombre"%><br>
      <%= f.text_field :name , class:"form-control"%>
    </div>
  </div>

  <div class="form-group col-md-12">
    <div class="col-md-12">
      <%= f.label :description , "Descripción"%><br>
      <%= f.text_area :description , class:"form-control"%>
    </div>
  </div>
  <div class="form-group col-md-12">
    <div class="col-md-12">
      <%= button_tag(:type => 'submit', :class => 'btn btn-dark') do %>
        <i class="glyphicon glyphicon-floppy-disk"></i>
        Editar sublote 
      <% end %>
      <%= link_to admin_sublots_path ,:class =>"btn btn-danger" do %>
          <span class="glyphicon glyphicon-remove"></span>
          Cancelar
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/sublots/index.html.erb
<%= javascript_include_tag 'jquery.dataTables.min', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'bootstrap', 'data-turbolinks-track' => true %>

<h1 class="x_title">
  <i class="glyphicon glyphicon-leaf titleicon"></i>
  Listar Sublotes
</h1>

<%= link_to new_admin_sublot_path , :class =>"btn btn-dark pull-right" do %>
  <span class="glyphicon glyphicon-plus"></span>
  Crear sublote
<% end %>

<table id="datatable" class="display datatable" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Centro de costos</th>
      <th>Código</th>
      <th>Nombre</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @sublots.each do |sublot| %>
      <tr>
        <td><%= sublot.costc.name %></td>
        <td><%= sublot.code %></td>
        <td><%= sublot.name %></td>
        <td>

        <%= link_to admin_sublot_path(sublot),:class =>"btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-eye-open"></span>
          Ver
        <% end %>

        <%= link_to edit_admin_sublot_path(sublot),:class =>"btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-pencil"></span>
          Editar
        <% end %>

        <%= link_to admin_sublot_path(sublot),:class =>"btn btn-default btn-sm", method: :delete, data: { confirm: '¿Seguro desea eliminar el sublote?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
          Eliminar
        <% end %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
$('#datatable').DataTable({
              "language": {
                "url": "../files/spanish"
            }
  // ajax: ...,
  // autoWidth: false,
  // pagingType: 'full_numbers',
  // processing: true,
  // serverSide: true,

  // Optional, if you want full pagination controls.
  // Check dataTables documentation to learn more about available options.
  // http://datatables.net/reference/option/pagingType
});
</script>

app/views/admin/sublots/new.html.erb
<h1 class="x_title">
  <i class="glyphicon glyphicon-leaf titleicon"></i>
  Crear Sublote
</h1>

<%= form_for @sublot , url:{action: "create"} do |f| %>
  <% if @sublot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sublot.errors.count, "error") %> prohibited this sublot from being saved:</h2>
      <ul>
        <% @sublot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group col-md-12">
    <div class="col-md-4">
        <%= f.label :costc_id, "Centro de costo" %>
        <%= f.select :costc_id, Costc.all.map { |j|  [ j.name , j.id ]  } , {prompt: ""} ,class:"form-control"%>
    </div>
    <div class="col-md-4">
      <%= f.label :code , "Código"%>
      <%= f.text_field :code , class:"form-control"%>
    </div>
    <div class="col-md-4">
      <%= f.label :name , "Nombre"%>
      <%= f.text_field :name , class:"form-control"%>
    </div>
  </div>

  <div class="form-group col-md-12">
    <div class="col-md-12">
      <%= f.label :description , "Descripción"%>
      <%= f.text_area :description , class:"form-control"%>
    </div>
  </div>

  <div class="form-group col-md-12"> 
    <div class="col-md-12">
      <%= button_tag(:type => 'submit', :class => 'btn btn-dark') do %>
        <i class="glyphicon glyphicon-floppy-disk"></i>
        Crear sublote 
      <% end %>
      <%= link_to admin_sublots_path ,:class =>"btn btn-danger" do %>
          <span class="glyphicon glyphicon-remove"></span>
          Cancelar
      <% end %>
    </div>
  </div>
<% end %>

app/views/admin/sublots/show.html.erb
<div class="x_panel">

  <h1 class="x_title">
    <i class="glyphicon glyphicon-leaf titleicon"></i>
    Sublote: <%= @sublot.name %>
  </h1>

  <% if @sublot.costc_id.present? %>
  	<p>
  	  <strong>Centro de costos:</strong>
  	  <%= @sublot.costc.name %>
  	</p>
  <% end %>

  <p>
    <strong>Código:</strong>
    <%= @sublot.code %>
  </p>

  <p>
    <strong>Descripción:</strong>
    <%= @sublot.description %>
  </p>

  <%= link_to edit_admin_sublot_path(@sublot) ,:class =>"btn btn-dark" do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <%= link_to admin_sublots_path ,:class =>"btn btn-danger" do %>
    <span class="glyphicon glyphicon-remove"></span>
    Cancelar
  <% end %>
</div>